# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# node.js development box
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  # Ports, if you wish
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  #vbguest plugin config
  if Vagrant.has_plugin?("vagrant-vbguest")
    # set to false to disable vbguest from updating guest additions
    config.vbguest.auto_update = true
  end

  # Virtualbox settings
  # 6 gigs ram. Don't use more than 50% of the host's cpu
  config.vm.provider "virtualbox" do |vb|
    vb.name = "node-devbox"
    vb.memory = "6114"
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

  # install docker
  config.vm.provision "docker" do |docker|
  end

  config.vm.provision "dev-tools", type: "shell", path: "provision/dev-tools.sh", privileged: false
  config.vm.provision "node", type: "shell", path: "provision/node.sh", privileged: false

end
